# eBay search configuration
search_term = "PROART‑RTX4060TI‑O16G"  # Your search term
max_price = 575.00  # Maximum price in USD
blocked_words = [
    "for parts",
    "defective",
    "broken",
    "not working",
    "box only",
    "rusted",
    "parts only",
    "untested"
]

# Telegram configuration
chat_id = "7612158612"  # Your Telegram chat ID (will be set via environment variable) 
